name: Build and Deploy Docker to Azure

on:
  push:
    branches:
      - main  # Trigger the pipeline on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set this in your repo secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set this in your repo secrets

      # Build the Docker image
      - name: Build Docker image
        run: docker build . -t pranjalrmcf7/app:latest

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push pranjalrmcf7/app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure using Azure CLI
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Set the Azure credentials in your repo secrets

      # Deploy the Docker container to Azure App Service
      - name: Deploy Docker image to Azure Web App
        run: |
          az webapp config container set --name ${{ secrets.AZURE_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --docker-custom-image-name pranjalrmcf7/app:latest \
            --docker-registry-server-url https://index.docker.io/v1/ \
            --docker-registry-server-user ${{ secrets.DOCKER_USERNAME }} \
            --docker-registry-server-password ${{ secrets.DOCKER_PASSWORD }}
